name: The Magic - Journey To Gratitude
favicon: null
layout_spectrum: 0.99717
typography_spectrum: 0.27822
title: The Magic - Journey To Gratitude
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d3236'
    - '#efe9d1'
    - '#856a5f'
    - '#710326'
    - '#c3954c'
  brandStrength: 0.8285550826694816
  lightness: 0.20739452075213194
  saturation: 0.7260074252262712
  rhythmicContrast: 0.217896735528484
purpose: []
